apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}-simple-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.name }}
    namespace: default
  project: default
  source:
    path: simple-b
    repoURL: https://github.com/larkintuckerllc/argocd-app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
  