apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-b
  namespace: argocd
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: simple-b
    repoURL: https://github.com/larkintuckerllc/argocd-app-of-apps
    targetRevision: HEAD
